# Configuration de base
sonar.projectKey=pre-pfe
sonar.projectName=Pre-PFE Project
sonar.projectVersion=1.0

# Sources à scanner
sonar.sources=backend,frontend/src

# EXCLUSIONS CRITIQUES (pour ignorer node_modules et les rapports de coverage)
sonar.exclusions=**/node_modules/**, **/coverage/**, **/*.html, **/*.css, frontend/dist/**, backend/dist/**

# Chemins vers les rapports de tests (si applicables)
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
